### ISSUE TITLE
mistake on Readme

### ISSUE THREAD

**Issue by iman01** [aussierobots/ublox_dgnss#22]
(vendor ID of 0x1546 and product ID of **0x1546**).
is wrong in readme , ublox product id is 0x01a9
as in code 
#define F9_VENDOR_ID      0x1546   // U-Blox AG
#define F9_PRODUCT_ID     0x01a9   // u-blox GNSS receiver

**Comment by hortovanyi** [comment]
Have applied the change. Thanks for picking it up
